### ISSUE TITLE
 failed to index block at height 330572

### ISSUE THREAD

**Issue by vikiival** [vikiival/unique#6]
```bash
failed to index block at height 330572 handleEventMaster([{"phase":{"applyExtrinsic":0},"event":{"index":"0x330e","data":[0]},"topics":[]}]) Error at Query.run (/usr/local/lib/node_modules/@subql/node/node_modules/sequelize/lib/dialects/postgres/query.js:76:25) at /usr/local/lib/node_modules/@subql/node/node_modules/sequelize/lib/sequelize.js:626:28 at processTicksAndRejections (internal/process/task_queues.js:95:5) at async PostgresQueryInterface.upsert (/usr/local/lib/node_modules/@subql/node/node_modules/sequelize/lib/dialects/abstract/query-interface.js:805:12) at async Function.upsert (/usr/local/lib/node_modules/@subql/node/node_modules/sequelize/lib/model.js:2501:20) at async Object.set (/usr/local/lib/node_modules/@subql/node/dist/indexer/store.service.js:260:17)
```

**Comment by vikiival** [comment]
```
subquery-node_1   | 2021-12-06T13:47:45.741Z <sandbox> INFO [MASTER] {
subquery-node_1   |   "id": "2",
subquery-node_1   |   "method": "AssetStatusChanged",
subquery-node_1   |   "section": "uniques"
subquery-node_1   | }
subquery-node_1   | 2021-12-06T13:47:45.741Z <sandbox> WARN !! BAD ROOT in block {
subquery-node_1   |   "caller": "CaKWz5omakTK7ovp4m3koXrHyHb7NG3Nt7GENHbviByZpKp",
subquery-node_1   |   "blockNumber": "330572",
subquery-node_1   |   "timestamp": "2021-07-15T12:22:18.464Z"
subquery-node_1   | }
```

Somehow the chain is getting this magic extrinsic arg: 
There are two possibilities: 
- [ ] The args changed ?
- [ ] Someone made XCMP transfer

```json
{
  "validationData": {
    "parentHead": "0xb9543daefd4a379b018e386a05b3de9afd9031239ff32bd55fbcfae30f15b2e62e2d140044737b5b35f03d240a90986a5af9607d547b9f69b78970d85e4394996b37114082f0757ef9bb96acc913f2a7e2ef5cfed3d058e225931fc3329d2b6599903009080661757261205e0314080000000005617572610101d8d4e3cde79dd0281df612bd2005db566574c0dc76a50fa06fad304b60436735f22a73fce5f654529f192fc486e3abb4ada48da8639c04084c77adb7fe581181",
    "relayParentNumber": 8354454,
    "relayParentStorageRoot": "0x356fb1643db2607fc138375438abfeda980cd49f68f5ba5a1fa5c8c7c198f81d",
    "maxPovSize": 5242880
  },
  "relayChainState": {
    "trieNodes": [
      "0x9f0d7fefc408aac59dbfe80a72ac8e3ce540088016e5ff511b17dadda363068b70ed0704e906b143ad56412f08fd9782cd86895c80b33956776594c5742ad4565566a675d8479c0b341d896ce3ff8b23e833459b8d",
      "0x800814800f7cf9bfe8050918e4199ebfe0b257ce745acee41b6cd4cc32799c11c6edc55980f1226e3e5ef00ecfb66e578dee238b19c99ab261ff16af60279cea09a2fbd39680aa8abe3a063603c5b49e7fce28dad5cbd42261c8fce8098a1839b6dc0b148223",
      "0x7ede3d8a54d27e44a9d5ce189618f22db4b49d95320d9021994c850f25b8e385f9020000a000005000000a00000000c8000000c800000a0000000a00000040380000580200000000500000c8000000e87648170000000a0000000000000002000000c09e5d9a2f3d00000000000000000000c09e5d9a2f3d00000000000000000000e8030000009001000a00000000000000009001008070000000000000000000000a0000000a0000000a00000001000000010500000001c8000000060000005802000002000000580200000200000059000000000000001e00000028000000",
      "0x804008808b84786d3667c452ed857216d2e7b5e3bac13edf4af4a2ae78a2feff6bd1a89280500c3e1fadcbf6a663b0c8c37a91eb3b24271e37efb19904106badc43a7010b8",
      "0x5706ff6f7d467b87a9e803000080a9ddfb6ea3020b880e4da74e8fbbe5242984055519fed897060b5538e2fbd61b",
      "0x7e207f03cfdce586301014700e2c2593eec2d17a76153ff51817f12d9cfc3c7f0400",
      "0x9ef78c98723ddc9073523ef3beefda0c10048045ebb1737a039e48959fc9b80ebb0d16179c371f8814865aea4c3992a9512974805ceb065187e45bd29d228ae7e8d5454ae230347d0d3f6e6ee42b1a6a77696733",
      "0x806500802f2e566c53b68cf40203ce86f296fdb82c7155c62bcaf93f2d8da3240ea86563802f2226bc2f2e81da7db29551b613c14aa9e61dd3810ed83ce2ae16b6e0b8a282809f284a86f45e0802b1d3be101948799c566e6927487026cf11fa7b27c5ed045d801d8c6bd56b9fbc94a728b0a2426bcb15979b1dff2dd66515d152a91124ea933f",
      "0x9eb6f36e027abb2091cfb5110ab5087fe96f685f06155b3cd9a8c9e5e9a23fd5dc13a5ed20bf06281000000000685f08316cbf8fa0da822a20ac1c55bf1be320c23700000000000080bee5ea2481ea0d24415032537aa0314724382a5559c7267169ca199cca781340805ceed45b84557f98455afdf7518e1b07fa8e0eda7f680fb5415dd0a3bf656bf180f779b89665d78858069a75bf3e15cee9e00ee52f5699467476e8450ebc35ca04585f078d434d6125b40443fe11fd292d13a41003000000800d49fef039517cc312c00412803ca1df50ac6d90c50541f649a9c85b83c0fdd8804d117f0ad6f3f53ecab3c865ac98ab680f80509a953f982f7060673452533774808035872a7c321710fd0f2b44e3cc202455c87c0963320a6abc0408416f1b7bc480fbfda55793b3c6931dcfd90fd1a9f341e9474dbb9e237e6ba7d416f94e23c583685f090e2fbf2d792cb324bffa9427fe1f0e2021767f0076787f00",
      "0x80131780255e5377495298ffb4ed642c7e50b53870f536919a4408c597b1e565664dc4058016da33d5274df1c180132a1965a499a854aaefad1951db6ce85752976453d1ca80989783ca2ecf0db9def32437c785585684864536c85c7a058824436e0777efa180351aec7ec0dc8a45abf666ca3b4ffd4990c94b8d5ea07544ba34c11dd7c06ece8088ed6db3417b4c7f2012924ba9ab60f0f27d57671ad9ec38ee0317b60a2c28cc80594dfba4fefdbf0d2ed4b7dc454151290b32cf782e25b135c33fb43b453ea47e809d9561d1930d6dfbf8d9db733baa877e1c5a22bafeaf147b9728960f0c6f0879",
      "0x9d0da05ca59913bc38a8630590f2627c014080d1167c6e48c6b8d98675ade0e9b9194312324f29e6eab5430d8c61e9802c66df80044f3ba762f0253167acc862997437a6305a5244d84163a8cfc4a7264a6111b4",
      "0x80011080513a2c401a32da7a972d55ae0c6e91cca888e9c807db71edbc14d4bd7765691e807597d4415b05773394bbcb5e796a531a07f4d840f77555702b4b3230bdf18f1a",
      "0x80ffff80d8aa347f33e556b5018feb13fc9bfdb72f79874c641c862390f93a27a69f9190808fd70a4e4469e53d678ae9942e4fbe60bb840abccaa49646ba4e818527c1aac380afa0bb47f6916287bbb0141b2f5d48a03e17b3779b2d93aba70a1d35b823165180069578cc128f61f85e7ded64e44aa5e65e7c8efd69c55460b67f414342f6ea69804f1312e620ad752e68c02a5b3f79e4e9ed3aa6aaa8423b099862147fcff7737e805a52ff73dbc89f3dcb97449abb5255f0759bfc5efc89f8a677b6e9bc6273d68080063c0e0d5441095ead29d81628eed5efa2400d979931a4b71c1ff212f7be1f7880e9f812938a63aec5fe9d91e15c770a8c50411fab95202a20e2214e2f3c14825180caf32e96859311d04f2a43c7cbd9ba5feab48f458fa39d8873087e2e96e3438b807cbc647135632d580ba59ee2a5e0a30d9607688bfc9904ba80e64ef7e99bebc080c5737c64715d348fd4895e44b21da05896166e442ca032778be6d3aee5c1e21f8094bf0a8bcf9d571c1c34332d3258a9da7bbcfeb2fd835a36e9a2600624d99069808e0df614fc05d0575c26b4d8d5553d0c9024fa74906df4bc5985e6376cd33e27805130271aba0b95f45edbf8e8293b0705338e46eca8ba2421d53308ce4e488c4c80dc493acafbc7d10dcacec4a8dc50411142db0e37641704623470ef1a5a87bb0a80ababf34d7995a34aa3a762d025c08e47bc8ec12e64d04c1c9495becc1f67139a"
    ]
  },
  "downwardMessages": [
    {
      "pubSentAt": 8354454,
      "pubMsg": "0x000a01090302304c06030010a5d4e8000000790628000c330f0000742c3dc19f0578c6b3094a2b8d5df46f01f6ac5c49fabbdb9ecaf16c385258f600742c3dc19f0578c6b3094a2b8d5df46f01f6ac5c49fabbdb9ecaf16c385258f600742c3dc19f0578c6b3094a2b8d5df46f01f6ac5c49fabbdb9ecaf16c385258f600742c3dc19f0578c6b3094a2b8d5df46f01f6ac5c49fabbdb9ecaf16c385258f60100330f0400742c3dc19f0578c6b3094a2b8d5df46f01f6ac5c49fabbdb9ecaf16c385258f600742c3dc19f0578c6b3094a2b8d5df46f01f6ac5c49fabbdb9ecaf16c385258f600742c3dc19f0578c6b3094a2b8d5df46f01f6ac5c49fabbdb9ecaf16c385258f600742c3dc19f0578c6b3094a2b8d5df46f01f6ac5c49fabbdb9ecaf16c385258f60100330f0800742c3dc19f0578c6b3094a2b8d5df46f01f6ac5c49fabbdb9ecaf16c385258f600742c3dc19f0578c6b3094a2b8d5df46f01f6ac5c49fabbdb9ecaf16c385258f600742c3dc19f0578c6b3094a2b8d5df46f01f6ac5c49fabbdb9ecaf16c385258f600742c3dc19f0578c6b3094a2b8d5df46f01f6ac5c49fabbdb9ecaf16c385258f60100"
    }
  ],
  "horizontalMessages": {}
}

```
